const config = {
    "hostSDK": {
        "sandbox": "https://sdk-sandbox.joinsherpa.io",
        "production": "https://sdk.joinsherpa.io"
    },    
    "element": {
        "trip": "Trip Element",
        //"map": "Map Element"
    },    
    "placement": {
        "homePage": "Home Page",
        "discovery": "Generic pre-booking marketing page",
        "mmb": "Manage My Booking",
        "search": "Search",
        "bookingConfirmation": "Booking Confirmation",
        "destinationPage": "Dedicated marketing page for a destination",
        "covidPage": "Dedicated page for COVID-19 resources"
    },
    "language": {
        "ar-SA": "Arabic",
        "zh-CN": "Chinese, Simplified",
        "zh-TW": "Chinese, Traditional",
        "da-DK": "Danish",
        "nl-NL": "Dutch",
        "en-US": "English, American",
        "en-CA": "English, Canada",
        "en-GB": "English, United Kingdom",
        "fi-FI": "Finnish",
        "fr-CA": "French, Canadian",
        "fr-FR": "French, France",
        "de-DE": "German",
        "is-IS": "Icelandic",
        "id-ID": "Indonesian",
        "it-IT": "Italian",
        "ja-JP": "Japanese",
        "ko-KR": "Korean",
        "lv-LV": "Latvian",
        "ms-MY": "Malay",
        "no-NO": "Norwegian",
        "pl-PL": "Polish",
        "pt-BR": "Portuguese, Brazilian",
        "pt-PT": "Portuguese, Portugal",
        "ru-RU": "Russian",
        "es-ES": "Spanish Spain",
        "es-XL": "Spanish, Latin America",
        "sv-SE": "Swedish",
        "th-TH": "Thai",
        "tr-TR": "Turkish",
        "vi-VN": "Vietnamese"
    }, 
    "country": {
        "ALA": "Aaland Islands",
        "AFG": "Afghanistan",
        "ALB": "Albania",
        "DZA": "Algeria",
        "ASM": "American Samoa",
        "AND": "Andorra",
        "AGO": "Angola",
        "AIA": "Anguilla",
        "ATG": "Antigua and Barbuda",
        "ARG": "Argentina",
        "ARM": "Armenia",
        "ABW": "Aruba",
        "AUS": "Australia",
        "AUT": "Austria",
        "AZE": "Azerbaijan",
        "BHS": "Bahamas",
        "BHR": "Bahrain",
        "BGD": "Bangladesh",
        "BRB": "Barbados",
        "BLR": "Belarus",
        "BEL": "Belgium",
        "BLZ": "Belize",
        "BEN": "Benin",
        "BMU": "Bermuda",
        "BTN": "Bhutan",
        "BOL": "Bolivia",
        "BES": "Bonaire, Sint Eustatius and Saba",
        "BIH": "Bosnia and Herzegovina",
        "BWA": "Botswana",
        "BRA": "Brazil",
        "VGB": "British Virgin Islands",
        "BRN": "Brunei",
        "BGR": "Bulgaria",
        "BFA": "Burkina Faso",
        "BDI": "Burundi",
        "KHM": "Cambodia",
        "CMR": "Cameroon",
        "CAN": "Canada",
        "CPV": "Cape Verde",
        "CYM": "Cayman Islands",
        "CAF": "Central African Republic",
        "TCD": "Chad",
        "CHL": "Chile",
        "CHN": "China",
        "CCK": "Cocos (Keeling) Islands",
        "COL": "Colombia",
        "COM": "Comoros",
        "COK": "Cook Islands",
        "CRI": "Costa Rica",
        "CIV": "Cote d'Ivoire (Ivory Coast)",
        "HRV": "Croatia",
        "CUB": "Cuba",
        "CUW": "Curacao",
        "CYP": "Cyprus",
        "CZE": "Czechia",
        "COD": "Democratic Republic of the Congo",
        "DNK": "Denmark",
        "DJI": "Djibouti",
        "DMA": "Dominica",
        "DOM": "Dominican Republic",
        "ECU": "Ecuador",
        "EGY": "Egypt",
        "SLV": "El Salvador",
        "GNQ": "Equatorial Guinea",
        "ERI": "Eritrea",
        "EST": "Estonia",
        "SWZ": "Eswatini",
        "ETH": "Ethiopia",
        "FLK": "Falkland Islands",
        "FRO": "Faroe Islands",
        "FJI": "Fiji",
        "FIN": "Finland",
        "FRA": "France",
        "PYF": "French Polynesia",
        "GAB": "Gabon",
        "GMB": "Gambia",
        "GEO": "Georgia",
        "DEU": "Germany",
        "GHA": "Ghana",
        "GIB": "Gibraltar",
        "GRC": "Greece",
        "GRL": "Greenland",
        "GRD": "Grenada",
        "GLP": "Guadeloupe",
        "GUM": "Guam",
        "GTM": "Guatemala",
        "GGY": "Guernsey",
        "GIN": "Guinea",
        "GNB": "Guinea-Bissau",
        "GUY": "Guyana",
        "HTI": "Haiti",
        "HND": "Honduras",
        "HKG": "Hong Kong",
        "HUN": "Hungary",
        "ISL": "Iceland",
        "IND": "India",
        "IDN": "Indonesia",
        "IRN": "Iran",
        "IRQ": "Iraq",
        "IRL": "Ireland",
        "IMN": "Isle of Man",
        "ISR": "Israel",
        "ITA": "Italy",
        "JAM": "Jamaica",
        "JPN": "Japan",
        "JEY": "Jersey",
        "JOR": "Jordan",
        "KAZ": "Kazakhstan",
        "KEN": "Kenya",
        "KIR": "Kiribati",
        "RKS": "Kosovo",
        "KWT": "Kuwait",
        "KGZ": "Kyrgyzstan",
        "LAO": "Laos",
        "LVA": "Latvia",
        "LBN": "Lebanon",
        "LSO": "Lesotho",
        "LBR": "Liberia",
        "LBY": "Libya",
        "LIE": "Liechtenstein",
        "LTU": "Lithuania",
        "LUX": "Luxembourg",
        "MAC": "Macao",
        "MDG": "Madagascar",
        "MWI": "Malawi",
        "MYS": "Malaysia",
        "MDV": "Maldives",
        "MLI": "Mali",
        "MLT": "Malta",
        "MHL": "Marshall Islands",
        "MTQ": "Martinique",
        "MRT": "Mauritania",
        "MUS": "Mauritius",
        "MYT": "Mayotte",
        "MEX": "Mexico",
        "FSM": "Micronesia",
        "MDA": "Moldova",
        "MCO": "Monaco",
        "MNG": "Mongolia",
        "MNE": "Montenegro",
        "MSR": "Montserrat",
        "MAR": "Morocco",
        "MOZ": "Mozambique",
        "MMR": "Myanmar",
        "NAM": "Namibia",
        "NRU": "Nauru",
        "NPL": "Nepal",
        "NLD": "Netherlands",
        "NCL": "New Caledonia",
        "NZL": "New Zealand",
        "NIC": "Nicaragua",
        "NER": "Niger",
        "NGA": "Nigeria",
        "NIU": "Niue",
        "PRK": "North Korea",
        "NX": "Northern Cyprus",
        "MKD": "Northern Macedonia",
        "MNP": "Northern Mariana Islands",
        "NOR": "Norway",
        "OMN": "Oman",
        "PAK": "Pakistan",
        "PLW": "Palau",
        "PSE": "Palestine",
        "PAN": "Panama",
        "PNG": "Papua New Guinea",
        "PRY": "Paraguay",
        "PER": "Peru",
        "PHL": "Philippines",
        "PCN": "Pitcairn Islands",
        "POL": "Poland",
        "PRT": "Portugal",
        "PRI": "Puerto Rico",
        "QAT": "Qatar",
        "COG": "Republic of the Congo",
        "REU": "Reunion",
        "ROU": "Romania",
        "RUS": "Russia",
        "RWA": "Rwanda",
        "BLM": "Saint Barthelemy",
        "SHN": "Saint Helena, Ascension, and Tristan da Cunha",
        "KNA": "Saint Kitts and Nevis",
        "LCA": "Saint Lucia",
        "MAF": "Saint Martin (French part)",
        "SPM": "Saint Pierre and Miquelon",
        "VCT": "Saint Vincent and the Grenadines",
        "WSM": "Samoa",
        "SMR": "San Marino",
        "STP": "Sao Tome and Principe",
        "SAU": "Saudi Arabia",
        "SEN": "Senegal",
        "SRB": "Serbia",
        "SYC": "Seychelles",
        "SLE": "Sierra Leone",
        "SGP": "Singapore",
        "SXM": "Sint Maarten",
        "SVK": "Slovakia",
        "SVN": "Slovenia",
        "SLB": "Solomon Islands",
        "SOM": "Somalia",
        "ZAF": "South Africa",
        "SGS": "South Georgia and the South Sandwich Islands",
        "KOR": "South Korea",
        "SSD": "South Sudan",
        "ESP": "Spain",
        "LKA": "Sri Lanka",
        "SDN": "Sudan",
        "SUR": "Suriname",
        "SJM": "Svalbard and Jan Mayen",
        "SWE": "Sweden",
        "CHE": "Switzerland",
        "SYR": "Syria",
        "TWN": "Taiwan",
        "TJK": "Tajikistan",
        "TZA": "Tanzania",
        "THA": "Thailand",
        "TLS": "Timor-Leste",
        "TGO": "Togo",
        "TON": "Tonga",
        "TTO": "Trinidad and Tobago",
        "TUN": "Tunisia",
        "TCA": "Turks and Caicos",
        "TUV": "Tuvalu",
        "TUR": "Türkiye",
        "UGA": "Uganda",
        "UKR": "Ukraine",
        "ARE": "United Arab Emirates",
        "GBR": "United Kingdom",
        "USA": "United States",
        "UMI": "United States Minor Outlying Islands",
        "VIR": "United States Virgin Islands",
        "URY": "Uruguay",
        "UZB": "Uzbekistan",
        "VUT": "Vanuatu",
        "VAT": "Vatican City",
        "VEN": "Venezuela",
        "VNM": "Vietnam",
        "YEM": "Yemen",
        "ZMB": "Zambia",
        "ZWE": "Zimbabwe",
        "Zimbabwe": "ZWE"        
    },
    "airport": {
        "ZNZ": "Abeid Amani Karume International Airport",
        "CJS": "Abraham González International Airport",
        "ADD": "Addis Ababa Bole International Airport",
        "MEX": "Aeropuerto Internacional Benito Juárez",
        "AMD": "Ahmedabad",
        "AWZ": "Ahvaz International Airport (Ahvaz)",
        "AKC": "Akron Fulton International Airport",
        "CAK": "Akron–Canton Airport",
        "ALB": "Albany International Airport",
        "ABQ": "Albuquerque International Sunport",
        "ALA": "Almaty International Airport",
        "MJN": "Amborovy Airport",
        "ATQ": "Amritsar",
        "DYR": "Anadyr (Ugolny Airport)",
        "TGZ": "Angel Albino Corzo International Airport",
        "ATW": "Appleton International Airport",
        "DIE": "Arrachart Airport",
        "ACY": "Atlantic City International Airport",
        "AUS": "Austin-Bergstrom International Airport",
        "IXB": "Bagdogra",
        "HUX": "Bahías de Huatulco International Airport",
        "BAH": "Bahrain International Airport",
        "BWI": "Baltimore-Washington International Thurgood Marshall Airport",
        "BND": "Bandar Abbas International Airport (Bandar Abbas)",
        "BGR": "Bangor International Airport",
        "BLR": "Bengaluru",
        "BBI": "Bhubaneshwar",
        "BHM": "Birmingham-Shuttlesworth International Airport",
        "BQS": "Blagoveschensk",
        "BDL": "Bradley International Airport",
        "BUF": "Buffalo Niagara International Airport",
        "YYC": "Calgary International Airport ",
        "CCJ": "Calicut",
        "CXR": "Cam Ranh Int Airport (Khanh Hoa)",
        "VCA": "Can Tho International Airport",
        "CUN": "Cancún International Airport",
        "LAN": "Capital Region International Airport",
        "VSA": "Carlos Rovirosa Pérez International Airport",
        "HPH": "Cat Bi Int Airport (Hai Phong)",
        "IXC": "Chandigarh",
        "IXC": "Chandigarh",
        "CHS": "Charleston International Airport",
        "CLT": "Charlotte/Douglas International Airport",
        "MAA": "Chennai",
        "CTM": "Chetumal International Airport",
        "CNX": "Chiang Mai International",
        "CNX": "Chiang Mai International",
        "MDW": "Chicago Midway International Airport",
        "RFD": "Chicago Rockford International Airport",
        "CZA": "Chichen Itza International Airport",
        "HTA": "Chita",
        "CVG": "Cincinnati/Northern Kentucky International Airport",
        "ACN": "Ciudad Acuña International Airport",
        "CME": "Ciudad del Carmen International Airport",
        "CEN": "Ciudad Obregón International Airport",
        "CLE": "Cleveland Hopkins International Airport",
        "COK": "Cochin",
        "CJB": "Coimbatore",
        "CZM": "Cozumel International Airport",
        "DAD": "Da Nang International Airport",
        "DFW": "Dallas/Fort Worth International Airport",
        "DAY": "Dayton International Airport",
        "BJX": "Del Bajío International Airport",
        "NTR": "Del Norte International Airport",
        "DEL": "Delhi",
        "DEN": "Denver International Airport",
        "DSM": "Des Moines International Airport",
        "DTW": "Detroit Metropolitan Wayne County Airport",
        "DIA": "Doha International Airport",
        "GDL": "Don Miguel Hidalgo y Costilla International Airport",
        "DMK": "Don Mueang International",
        "DMK": "Don Mueang International",
        "DZA": "Dzaoudzi–Pamandzi International Airport",
        "YEG": "Edmonton International Airport ",
        "OMA": "Eppley Airfield",
        "FAI": "Fairbanks International Airport",
        "NOS": "Fascene Airport",
        "CUL": "Federal de Bachigualato International Airport",
        "LMM": "Federal del Valle del Fuerte International Airport",
        "FLL": "Fort Lauderdale-Hollywood International Airport",
        "TRC": "Francisco Sarabia International Airport",
        "FAT": "Fresno Yosemite International Airport",
        "YQX": "Gander International Airport ",
        "GAY": "Gaya",
        "TIJ": "General Abelardo L. Rodríguez International Airport",
        "MLM": "General Francisco J. Mujica International Airport",
        "TAM": "General Francisco Javier Mina International Airport",
        "DGO": "General Guadalupe Victoria International Airport",
        "VER": "General Heriberto Jara International Airport",
        "HMO": "General Ignacio Pesqueira Garcia International Airport",
        "GYM": "General José María Yáñez International Airport",
        "ACA": "General Juan N. Álvarez International Airport",
        "ZCL": "General Leobardo C. Ruiz International Airport",
        "REX": "General Lucio Blanco International Airport",
        "MTY": "General Mariano Escobedo International Airport",
        "MKE": "General Mitchell International Airport",
        "CVM": "General Pedro J. Méndez International Airport",
        "MZT": "General Rafael Buelna International Airport",
        "CUU": "General Roberto Fierro Villalobos International Airport",
        "MXL": "General Rodolfo Sánchez Taboada International Airport",
        "MAM": "General Servando Canales International Airport",
        "IAH": "George Bush Intercontinental Airport",
        "GOI": "Goa",
        "YQM": "Greater Moncton Roméo LeBlanc International Airport ",
        "ROC": "Greater Rochester International Airport",
        "GRB": "Green Bay–Austin Straubel International Airport",
        "GAU": "Guwahati",
        "YHZ": "Halifax Stanfield International Airport ",
        "DOH": "Hamad International Airport",
        "YHM": "Hamilton/John C. Munro International Airport ",
        "ATL": "Hartsfield-Jackson Atlanta International Airport",
        "PBC": "Hermanos Serdán International Airport",
        "ITO": "Hilo International Airport",
        "HNL": "Honolulu International Airport",
        "HSV": "Huntsville International Airport",
        "HDD": "Hyderabad",
        "SMS": "Île Sainte-Marie",
        "IKA": "Imam Khomeini International Airport (Tehran)",
        "IND": "Indianapolis International Airport",
        "CPE": "Ing. Alberto Acuña Ongay International Airport",
        "IFN": "Isfahan International Airport (Isfahan)",
        "TNR": "Ivato International Airport",
        "ZIH": "Ixtapa-Zihuatanejo International Airport",
        "JAX": "Jacksonville International Airport",
        "JAI": "Jaipur",
        "JFK": "John F. Kennedy International Airport",
        "CMH": "John Glenn Columbus International Airport",
        "SNA": "John Wayne Airport",
        "BUQ": "Joshua Mqabuko International Airport",
        "DAR": "Julius Nyerere International Airport ",
        "JNU": "Juneau International Airport",
        "KGD": "Kaliningrad",
        "KME": "Kamembe International Airport",
        "MCI": "Kansas City International Airport",
        "LKE": "Kenmore Air Harbor Seaplane Base",
        "KER": "Kerman Airport (Kerman)",
        "KTN": "Ketchikan International Airport",
        "EYW": "Key West International Airport",
        "KHV": "Khabarovsk (Novy Airport)",
        "KGL": "Kigali International Airport",
        "JRO": "Kilimanjaro International Airport ",
        "JED": "King Abdul-Aziz airport in Jeddah",
        "BFI": "King County International Airport",
        "DMM": "King Fahad airport in Dammam",
        "RUH": "King Khaled airport in Riyadh",
        "KIH": "Kish International Airport (Kish Island)",
        "CCU": "Kolkata",
        "KOA": "Kona International Airport",
        "KWI": "Kuwait International Airport",
        "LGA": "LaGuardia Airport",
        "LAL": "Lakeland Linder International Airport",
        "STL": "Lambert-Saint Louis International Airport",
        "LRR": "Larestan International Airport (Lar)",
        "LBV": "Léon-Mba International Airport",
        "TLC": "Lic. Adolfo López Mateos International Airport",
        "PVR": "Lic. Gustavo Díaz Ordaz International Airport",
        "AGU": "Lic. Jesús Terán Peredo International Airport",
        "BOS": "Logan International Airport",
        "YXU": "London International Airport ",
        "LTO": "Loreto International Airport",
        "LAX": "Los Angeles International Airport",
        "SJD": "Los Cabos International Airport",
        "MSY": "Louis Armstrong New Orleans International Airport",
        "SDF": "Louisville International Airport",
        "LPQ": "Luang Prabang International Airport (Luang Prabang Province)",
        "LPQ": "Luang Prabang International Airport (Luang Prabang Province)",
        "SDD": "Lubango Airport",
        "LKO": "Lucknow",
        "SJU": "Luis Munoz Marin International Airport",
        "IXM": "Madurai",
        "FRU": "Manas",
        "MDL": "Mandalay International Airport",
        "IXE": "Mangalore",
        "MID": "Manuel Crescencio Rejón International Airport",
        "LAP": "Manuel Márquez de León International Airport",
        "MHD": "Mashhad International Airport (Mashad)",
        "LAS": "McCarran International Airport",
        "THR": "Mehrabad International Airport (Tehran)",
        "MLB": "Melbourne International Airport",
        "MEM": "Memphis International Airport",
        "OAK": "Metropolitan Oakland International Airport",
        "MIA": "Miami International Airport",
        "MSP": "Minneapolis-Saint Paul International Airport",
        "YUL": "Montréal-Pierre Elliott Trudeau International Airport ",
        "MOQ": "Morondava Airport",
        "BOM": "Mumbai",
        "MWZ": "Mwanza International Airport",
        "MYR": "Myrtle Beach International Airport",
        "NAG": "Nagpur",
        "BNA": "Nashville International Airport",
        "NYT": "Nay Pyi Taw International Airport",
        "EWR": "Newark Liberty International Airport",
        "NOG": "Nogales International Airport",
        "HAN": "Noi Bai International Airport (Ha Noi)",
        "ECP": "Northwest Florida Beaches International Airport",
        "TSE": "Nursultan Nazarbayev International Airport",
        "ORD": "O'Hare International Airport",
        "ONT": "Ontario International Airport",
        "MCO": "Orlando International Airport",
        "SFB": "Orlando Sanford International Airport",
        "OSS": "Osh",
        "OXB": "Osvaldo Vieira International Airport",
        "YOW": "Ottawa Macdonald-Cartier International Airport ",
        "PAE": "Paine Field",
        "PQM": "Palenque International Airport",
        "PSP": "Palm Springs International Airport",
        "PKC": "Petropavlovsk-Kamchatsky (Yelizovo Airport)",
        "PHL": "Philadelphia International Airport",
        "PNH": "Phnom Penh International Airport",
        "PHX": "Phoenix Sky Harbor International Airport",
        "AZA": "Phoenix–Mesa Gateway Airport",
        "HUI": "Phu Bai Int Airport",
        "PQC": "Phu Quoc International Airport",
        "HKT": "Phuket International",
        "HKT": "Phuket International",
        "PDS": "Piedras Negras International Airport",
        "PIT": "Pittsburgh International Airport",
        "SLW": "Plan de Guadalupe International Airport",
        "ZLO": "Playa de Oro International Airport",
        "SLP": "Ponciano Arriaga International Airport",
        "IXZ": "Port Blair",
        "ABJ": "Port Bouët Airport (Abidjan)",
        "PDX": "Portland International Airport",
        "PWM": "Portland International Jetport",
        "MED": "Prince Mohammad Bin Abdulaziz International Airport",
        "PXM": "Puerto Escondido International Airport",
        "PPE": "Puerto Peñasco International Airport",
        "LED": "Pulkovo",
        "PNQ": "Pune",
        "GSM": "Qeshm international Airport (Qeshm Island) ",
        "LAD": "Quatro de Fevereiro Airport (Luanda)",
        "YQB": "Québec/Jean Lesage International Airport ",
        "QRO": "Querétaro International Airport",
        "NLD": "Quetzalcóatl International Airport",
        "RDU": "Raleigh-Durham International Airport",
        "YQR": "Regina International Airport ",
        "RNO": "Reno-Tahoe International Airport",
        "LCK": "Rickenbacker International Airport",
        "HRE": "Robert Gabriel Mugabe (Harare) International Airport",
        "RST": "Rochester International Airport",
        "SMF": "Sacramento International Airport",
        "SLC": "Salt Lake City International Airport",
        "SVB": "Sambava Airport",
        "SAT": "San Antonio International Airport",
        "SBD": "San Bernardino International Airport",
        "SAN": "San Diego International Airport",
        "SFH": "San Felipe International Airport",
        "SFO": "San Francisco International Airport",
        "SJC": "San Jose International Airport",
        "SRQ": "Sarasota-Bradenton International Airport",
        "YXE": "Saskatoon/John G. Diefenbaker International Airport ",
        "SEA": "Seattle-Tacoma International Airport",
        "LWN": "Shirak Airport (Gyumri, Shirak Province)",
        "SYZ": "Shiraz International Airport (Shiraz)",
        "REP": "Siem Reap International Airport",
        "KOS": "Sihanoukville International Airport",
        "RSW": "Southwest Florida International Airport",
        "GEG": "Spokane International Airport",
        "YYT": "St. John's International Airport ",
        "PIE": "St. Petersburg-Clearwater International Airport",
        "SWF": "Stewart International Airport",
        "BKK": "Suvarnabhumi International",
        "BKK": "Suvarnabhumi International",
        "SYR": "Syracuse Hancock International Airport",
        "PVD": "T.F. Green Airport",
        "TBZ": "Tabriz International Airport (Tabriz)",
        "SGN": "Tan Son Nhat Int Airport (Ho Chi Minh City)",
        "TAP": "Tapachula International Airport",
        "ANC": "Ted Stevens Anchorage International Airport",
        "TRZ": "Tiruchirappalli (Trichy)",
        "TMM": "Toamasina Airport",
        "TLE": "Toliara Airport",
        "YYZ": "Toronto Pearson International Airport ",
        "KTM": "Tribhuvan International Airport, Kathmandu",
        "TRV": "Trivandrum",
        "UUD": "Ulan-Ude",
        "OMH": "Urmia Airport (Urmia)",
        "UPN": "Uruapan International Airport",
        "YVR": "Vancouver International Airport ",
        "VNS": "Varanasi",
        "LOV": "Venustiano Carranza International Airport",
        "VFA": "Victoria Falls International Airport",
        "YYJ": "Victoria International Airport ",
        "VTZ": "Vishakhapatnam",
        "VVO": "Vladivostok (Knevichy Airport)",
        "VTE": "Wattay International Airport (Vientiane Capital)",
        "VTE": "Wattay International Airport (Vientiane Capital)",
        "HOU": "William P. Hobby Airport",
        "YWG": "Winnipeg International Airport ",
        "OAX": "Xoxocotlán International Airport",
        "RGN": "Yangon International Airport",
        "UUS": "Yuzhno-Sakhalinsk (Khomutovo Airport",
        "EVN": "Zvartnots International Airport (Yerevan)" 
    }

};

const htmlTemplate = `<!DOCTYPE html>
<html>
    <head>
        <script src="{{HOST_SDK}}/widget.js?appId={{APP_ID}}" async></script>
    </head>
    <body>

        <div id='sherpa-{{ELEMENT}}-element'></div>

        <script type='text/javascript'>

            const elementConfig = {
                {{ELEMENT_CONFIG}}

            };

            function onSherpaEvent(event) {
                if (event.type === 'sdkLoaded') {
                    $sherpa.V2.createElement('{{ELEMENT}}', elementConfig).mount('#sherpa-{{ELEMENT}}-element');
                }
            }

        </script>

    </body>
</html>`;

const travellerModel = `travellers: [{
    nationality: '{{PASSPORT}}',
    vaccinations: [{
        type: '{{VACCINATION_TYPE}}',
        status: '{{VACCINATION_STATUS}}'
    }]
}],`;

const segmentObject = `{
    segmentType: '{{SEGMENT_TYPE}}',
    origin: {
        {{ORIGIN_CODE}}: '{{ORIGIN_VALUE}}'
    },
    destination: {
        {{DESTINATION_CODE}}: '{{DESTINATION_VALUE}}'
    },
    travelMode: 'AIR',
    departureDate: '{{DEPARTURE_DATE}}',
    departureTime: '{{DEPARTURE_TIME}}',
    arrivalDate: '{{ARRIVAL_DATE}}',
    arrivalTime: '{{ARRIVAL_TIME}}'
}`